version: '3.4'

services:
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    container_name: Booking.Api
    build:
      context: .
      dockerfile: Booking.Api/Dockerfile
    depends_on: 
      - booking.db

  booking.db:
    image: postgres:latest
    container_name: Booking.Db
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  booking.idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Booking.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/booking-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "18080:8080"
        
  booking-seq:
    image: datalust/seq:latest
    container_name: Booking.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
